version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5002"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=jsonimport
      - MONGO_INITDB_DATABASE=customerinfo

volumes:
  mongo_data:
